steps:
  - name: 'gcr.io/vernal-aleph-410709/python-git-dvc'
    args: ['python', 'src/train_model.py']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/vernal-aleph-410709/trainer', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/vernal-aleph-410709/trainer']