steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/vernal-aleph-410709/trainer', '-f', './dockerfiles/trainer.dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/vernal-aleph-410709/trainer']
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/vernal-aleph-410709/predictor', '-f', './dockerfiles/predictor.dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/vernal-aleph-410709/predictor']