steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/vernal-aleph-410709/hello-world', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/vernal-aleph-410709/hello-world']