import pandas as pd
from sklearn import datasets
from evidently.report import Report
from evidently.metric_preset import DataDriftPreset
import pickle
import os

# Carica il dataset di training dal file .pkl
with open(f'{os.getcwd()}/data/processed/tokenized_train.pkl', 'rb') as file:
    dataset = pickle.load(file)

dataset = pd.DataFrame(dataset)
print(dataset[:20])
dataset.to_csv('C:/Users/Admin/Documents/HCAI/ML_OPERATIONS/MLOPS_final_Project/monitoring/datasettt.csv', index=False)
ref = pd.DataFrame(dataset[:60])
cur = pd.DataFrame(dataset[60:120])

# #load dataset generated by user's predictions
# current_data = pd.read_csv('prediction_database.csv')

# report = Report(metrics=[DataDriftPreset()])
# report.run(reference_data= ref, current_data = cur)
# report.save_html('report.html')