name: "T5-tests"

on:
  push:
    branches: [unit_test]
  pull_request:
    branches: [unit_test]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install DVC
      run: |
        pip install dvc
        pip install dvc_gdrive

    - name: Configure DVC and restore data
      run: |
        dvc pull  # Ripristina i dati gestiti da DVC

    - name: Test with pytest
      run: |
        pip install pytest
        pytest -v
